#!/bin/bash

echo "🚀 Setting up database for Expense Tracker..."
echo ""
echo "The current DATABASE_URL in server/.env is pointing to localhost, but PostgreSQL isn't running."
echo ""
echo "QUICKEST SOLUTION: Use a free cloud database"
echo ""
echo "1. Go to https://neon.tech"
echo "2. Create a free account (takes 30 seconds)"
echo "3. Create a new project called 'expense-tracker'"
echo "4. Copy the connection string they provide"
echo "5. Come back here and I'll help you update the .env file"
echo ""
echo "Alternative: Install PostgreSQL locally"
echo "If you have Homebrew installed, run:"
echo "  brew install postgresql"
echo "  brew services start postgresql"
echo "  createdb expense_tracker"
echo ""
echo "After setting up the database, update server/.env with the real connection string"
echo "and run: npm run test-db"
